on: push
jobs:
    build-project:
        name: Construccion del Proyecto 01
        runs-on: ubuntu-latest
        container: node:21.7.3
        steps:
            - name: Obtener version de NODE
              run: node --version
            - name: Obtener version de NPM
              run: npm --version
            - uses: actions/checkout@v4
            - run: npm install
            - name: No olvidar ejecutar la APP
              run: node app.js

